# Generated by Django 4.0.5 on 2023-09-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorgeneral',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='laboratorio',
            name='pais',
        ),
    ]
